### ISSUE TITLE
[БД] Хранение данных о пользователе

### ISSUE THREAD

**Issue by StretenskiyDanila** [StretenskiyDanila/recreation-assistant#6]
Необходимо реализовать хранение данных пользователя в базе данных. Используем БД H2.
О пользователе мы должны знать:
 - Имя
 - Город
 - Предпочтения к кухне (японская, французская и тд) 
 - Предпочтение к типу мероприятия (клуб, музей и тд)
 - Пьет алкоголь или нет

**Comment by JustReliks** [comment]
Создана база данных H2. Созданы миграции и Jpa репозитории.

Для захода в консоль базы данных (только при запущенном приложении): http://localhost:8080/h2-console/ Логин, пароль и адрес бд можно найти в файле application.yaml.
